config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  get 'dashboard/reports', as: 'reports'
  get 'dashboard/all_report', as: 'all_report'

  root 'dashboard#index'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'csv'

class User < ActiveRecord::Base
  has_many :meals
  has_many :pets

  def full_name
    "#{first_name} #{last_name}"
  end

  def last_first
    "#{last_name}, #{first_name}"
  end



#use self b/c calling the whole user class not an instance of the class
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @title = "People, Pets, and Meals | Dashboard"
    @users = User.all
  end

  def reports
  end

  def all_report
    respond_to do |format|
      format.csv do
        send_data User.to_csv, filename: 'users_report.csv', disposition: 'download'
      end
      format.html do
        render layout: false
        #did this because pdf wouldn't work with css to change it need to have them all going
        #to different paths
      end
      format.pdf do
        send_data PDFKit.new(all_report_url(format: 'html')), filename: 'all_report.pdf'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1><%= @title %></h1>
<%= link_to "Reports", reports_path %>
<hr>

<ul>
  <% @users.each do |user| %>
    <li>
      <h4><%= user.full_name %></h4>
      <strong>Meals</strong>
      <ul>
        <% user.meals.each do |meal| %>
          <li> <%= meal.name %></li>
        <% end %>
      </ul>
      <strong>Pets</strong>
      <ul>
        <% user.pets.each do |pet| %>
          <li> <%= pet.name %> </li>
        <% end %>
        </ul>
        </li>
        <% end %>
        </ul>

app/views/dashboard/reports.html.erb
<h1>Dashboard</h1>
<h2> Reports</h2>
<ul>
<li><%= link_to "All Report (as PDF)", all_report_path('pdf'), target: '_blank' %></li>
<li><%= link_to "All Report (as CSV)", all_report_path('csv') %></li>
<li><%= link_to "All Report (as HTML)", all_report_path() %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Report | #{controller.controller_name}" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>